[build]
publish = "/dist/apps/design-system"
node_bundler = "esbuild"

[functions]
directory = "functions/"

[[redirects]]
  from = "*"
  to = "http://localhost:4200"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"